name: cd
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Deploy with SSH
          uses: appleboy/ssh-action@master
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            script: | 
                cd /var/www/html/nextjstes 
                git pull origin master  
                yarn install --ignore-engines 
                yarn add @types/react --save
                yarn build 
                pm2 restart ecosystem.config.js
